model_architecture: NVLRformer
n_image_slots: 3
n_object_dims: 9
max_objects_per_scene: 8
max_question_tokens_per_scene: 30
num_token_types: 2
question_vocabulary_size: 188
hidden_dim: 128
num_attention_heads: 8
num_bert_layers: 4
num_output_classes: 1
max_epochs: 1000
batch_size: 128
lr: 0.0001
validate_every_epochs: 200
early_stopping: 5
mask_type: 1