model_architecture: NVLRformer
n_image_slots: 3
n_object_dims: 5
max_objects_per_scene: 8
max_question_tokens_per_scene: 30
num_token_types: 2
question_vocabulary_size: 188
hidden_dim: 128
num_attention_heads: 8
num_bert_layers: 5
num_output_classes: 2



max_epochs: 170
batch_size: 32
lr: 0.00005
max_lr: 0.0006
max_batch_size: 512
scheduler_step_size: 10
bs_scheduler_step_size: 10
scheduler_gamma: 1.5
bs_scheduler_gamma: 2
log_every: 500
validate_every: 20000
early_stopping: 10



n_workers: 0